function Cards(){
    cards = [
        {'pile': 'Hearts', 'value': 2, 'image':'cards/2H.svg'},
        {'pile': 'Hearts', 'value': 3, 'image':'cards/3H.svg'},
        {'pile': 'Hearts', 'value': 4, 'image':'cards/4H.svg'},
        {'pile': 'Hearts', 'value': 5, 'image':'cards/5H.svg'},
        {'pile': 'Hearts', 'value': 6, 'image':'cards/6H.svg'},
        {'pile': 'Hearts', 'value': 7, 'image':'cards/7H.svg'},
        {'pile': 'Hearts', 'value': 8, 'image':'cards/8H.svg'},
        {'pile': 'Hearts', 'value': 9, 'image':'cards/9H.svg'},
        {'pile': 'Hearts', 'value': 10, 'image':'cards/JH.svg'},
        {'pile': 'Hearts', 'value': 11, 'image':'cards/QH.svg'},
        {'pile': 'Hearts', 'value': 12, 'image':'cards/KH.svg'},
        {'pile': 'Hearts', 'value': 13, 'image':'cards/AH.svg'},
        {'pile': 'Diamond', 'value': 2, 'image':'cards/2D.svg'},
        {'pile': 'Diamond', 'value': 3, 'image':'cards/3D.svg'},
        {'pile': 'Diamond', 'value': 4, 'image':'cards/4D.svg'},
        {'pile': 'Diamond', 'value': 5, 'image':'cards/5D.svg'},
        {'pile': 'Diamond', 'value': 6, 'image':'cards/6D.svg'},
        {'pile': 'Diamond', 'value': 7, 'image':'cards/7D.svg'},
        {'pile': 'Diamond', 'value': 8, 'image':'cards/8D.svg'},
        {'pile': 'Diamond', 'value': 9, 'image':'cards/9D.svg'},
        {'pile': 'Diamond', 'value': 10, 'image':'cards/JD.svg'},
        {'pile': 'Diamond', 'value': 11, 'image':'cards/QD.svg'},
        {'pile': 'Diamond', 'value': 12, 'image':'cards/KD.svg'},
        {'pile': 'Diamond', 'value': 13, 'image':'cards/AD.svg'},
        {'pile': 'Sparrow', 'value': 2, 'image':'cards/2S.svg'},
        {'pile': 'Sparrow', 'value': 3, 'image':'cards/3S.svg'},
        {'pile': 'Sparrow', 'value': 4, 'image':'cards/4S.svg'},
        {'pile': 'Sparrow', 'value': 5, 'image':'cards/5S.svg'},
        {'pile': 'Sparrow', 'value': 6, 'image':'cards/6S.svg'},
        {'pile': 'Sparrow', 'value': 7, 'image':'cards/7S.svg'},
        {'pile': 'Sparrow', 'value': 8, 'image':'cards/8S.svg'},
        {'pile': 'Sparrow', 'value': 9, 'image':'cards/9S.svg'},
        {'pile': 'Sparrow', 'value': 10, 'image':'cards/JS.svg'},
        {'pile': 'Sparrow', 'value': 11, 'image':'cards/QS.svg'},
        {'pile': 'Sparrow', 'value': 12, 'image':'cards/KS.svg'},
        {'pile': 'Sparrow', 'value': 13, 'image':'cards/AS.svg'},
        {'pile': 'Clubs', 'value': 2, 'image':'cards/2C.svg'},
        {'pile': 'Clubs', 'value': 3, 'image':'cards/3C.svg'},
        {'pile': 'Clubs', 'value': 4, 'image':'cards/4C.svg'},
        {'pile': 'Clubs', 'value': 5, 'image':'cards/5C.svg'},
        {'pile': 'Clubs', 'value': 6, 'image':'cards/6C.svg'},
        {'pile': 'Clubs', 'value': 7, 'image':'cards/7C.svg'},
        {'pile': 'Clubs', 'value': 8, 'image':'cards/8C.svg'},
        {'pile': 'Clubs', 'value': 9, 'image':'cards/9C.svg'},
        {'pile': 'Clubs', 'value': 10, 'image':'cards/JC.svg'},
        {'pile': 'Clubs', 'value': 11, 'image':'cards/QC.svg'},
        {'pile': 'Clubs', 'value': 12, 'image':'cards/KC.svg'},
        {'pile': 'Clubs', 'value': 13, 'image':'cards/AC.svg'}
    ];
    return cards;
}
